### ISSUE TITLE
duck.CreatePatch cannot handle "remove" properly in some cases

### ISSUE THREAD

**Issue by yolocs** [knative/pkg#1060]
## Problem

https://github.com/knative/pkg/blob/master/apis/duck/patch.go uses `github.com/mattbaird/jsonpatch` which cannot handle json object removal properly and is no longer maintained upstream.

For example if I two podspec:

```
	p1 := &duckv1.WithPod{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "foo",
			Namespace: "foo-ns",
		},
		Spec: duckv1.WithPodSpec{
			Template: duckv1.PodSpecable{
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{
						{
							Name:    "curl-1",
							Image:   "governmentpaas/curl-ssl",
							Command: []string{"/bin/sleep", "3650d"},
							Env: []corev1.EnvVar{
								{
									Name:  "KEY1",
									Value: "VAL1",
								},
							},
						},
						{
							Name:    "curl-2",
							Image:   "governmentpaas/curl-ssl",
							Command: []string{"/bin/sleep", "3650d"},
							Env: []corev1.EnvVar{
								{
									Name:  "KEY2",
									Value: "VAL2",
								},
							},
						},
					},
				},
			},
		},
	}

	p2 := &duckv1.WithPod{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "foo",
			Namespace: "foo-ns",
		},
		Spec: duckv1.WithPodSpec{
			Template: duckv1.PodSpecable{
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{
						{
							Name:    "curl-1",
							Image:   "governmentpaas/curl-ssl",
							Command: []string{"/bin/sleep", "3650d"},
							Env: []corev1.EnvVar{
								{
									Name:  "KEY3",
									Value: "VAL3",
								},
							},
						},
					},
				},
			},
		},
	}
```

## Expected Behavior

I expect patch generated is something like

```
[
  {
    "op": "remove",
    "path": "/spec/template/spec/containers/1"
  },
  {
    "op": "replace",
    "path": "/spec/template/spec/containers/0/env",
    "value": [
      {
        "name": "KEY3",
        "value": "VAL3"
      }
    ]
  }
]
```

## Actual Behavior

Actual patch

```
[
  {
    "op": "remove",
    "path": "/spec/template/spec/containers/0"
  },
  {
    "op": "remove",
    "path": "/spec/template/spec/containers/1"
  },
  {
    "op": "add",
    "path": "/spec/template/spec/containers/0",
    "value": {
      "command": [
        "/bin/sleep",
        "3650d"
      ],
      "env": [
        {
          "name": "KEY3",
          "value": "VAL3"
        }
      ],
      "image": "governmentpaas/curl-ssl",
      "name": "curl-1",
      "resources": {}
    }
  }
]
```

This is not a valid patch because both containers are removed but the 3rd op trying to add to `0` index.

## Reproduce

Apply yaml.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curls
  annotations:
    security.knative.dev/authorizableOn: self
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curls
  template:
    metadata:
      labels:
        app: curls
    spec:
      containers:
      - name: curl-1
        image: governmentpaas/curl-ssl
        command: ["/bin/sleep", "3650d"]
        env:
          - name: "key1"
            value: "val1"
      - name: curl-2
        image: governmentpaas/curl-ssl
        command: ["/bin/sleep", "3650d"]
        env:
          - name: "key2"
            value: "val2"
```

Apply patch generated by `duck.CreatePatch`. See error.

```
kubectl patch deploy curls --type=json -p '[{"op":"remove","path":"/spec/template/spec/containers/0"},{"op":"remove","path":"/spec/template/spec/containers/1"},{"op":"add","path":"/spec/template/spec/containers/0","value":{"command":["/bin/sleep","3650d"],"env":[{"name":"KEY3","value":"VAL3"}],"image":"governmentpaas/curl-ssl","name":"curl-1","resources":{}}}]'
The request is invalid
```

Apply my expected patch. See success.

```
kubectl patch deploy curls --type=json -p '[{"op":"remove","path":"/spec/template/spec/containers/1"},{"op":"replace","path":"/spec/template/spec/containers/0/env","value":[{"name":"KEY3","value":"VAL3"}]}]'                           
deployment.extensions/curls patched
```

## Additional info

`duck.CreatePatch` is widely used in defaulting webhook which is probably fine because we usually just add stuff in these webhooks. `duck.CreatePatch` is also used in podspecable binding controller (https://github.com/knative/pkg/blob/master/webhook/psbinding/psbinding.go#L191). `bindable.Undo()` usually involves deleting stuff from a json object which could end up causing problems a lot more likely.

## Potential solution

* Use a properly maintained and supported json patch lib that handles removal correctly.
* Do/Undo in bindable could return `duck.JSONPatch` instead. This way allows the Do/Undo implementer to properly generate patch.
