### ISSUE TITLE
Components that are eligible for leaderelection should use anti-affinity

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#1269]
/area API
/kind feature
/kind good-first-issue

I noticed this in Contour's controller yaml, and I think it's probably a good pattern to follow:
```yaml
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: contour
              topologyKey: kubernetes.io/hostname
            weight: 100
```

Basically, if one of the HA scenarios you want to handle is disruptions due to node failures, then we should make sure that replicas of each component aren't scheduled on the same node as one another.

cc @pmorie for thoughts / alternatives
cc @lionelvillard @markusthoemmes @mgencur who have expressed interest in this space in other contexts FYI
