### ISSUE TITLE
Can user apply rules for validation webhook?

### ISSUE THREAD

**Issue by Yongxuanzhang** [knative/pkg#2467]
/kind question

## Expected Behavior

Hi, I tried to apply rules for the validation webhook (e.g. only validate on `CREATE`), but after reconciliation the user defined rules will be overwritten. I'm just curious what's the reason behind this? 

## Actual Behavior

By looking at the code, seems it will create new rules.

https://github.com/knative/pkg/blob/0a429cba1c73524035fafa46a9264311065d466e/webhook/resourcesemantics/validation/reconcile_config.go#L102-L118

## Steps to Reproduce the Problem
The configuration is something like this:
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook
webhooks:
- name: validation.webhook
  clientConfig:
    service:
      name: name
      namespace: ns
  rules:
  - apiGroups: ["xxx.dev"]
    apiVersions: ["v1beta1"]
    operations:  ["CREATE"]
    resources:   ["*/*"]
    scope:       "Namespaced"
  admissionReviewVersions: ["v1"]
  failurePolicy: Fail
  sideEffects: None
```
