### ISSUE TITLE
configmap.InformedWatcher need cluster role for listing configmap?

### ISSUE THREAD

**Issue by qibobo** [knative/pkg#977]
I am using the pkg(knative.dev/pkg v0.0.0-20191107185656-884d50f09454) to create a configmap watcher. 
```
configMapWatcher := configmap.NewInformedWatcher(kubeClient, configMapOps.Namespace)
configMapWatcher.Watch(configMapOps.ConfigMapName, updateExporter(component, logger))
if err = configMapWatcher.Start(ctx.Done()); err != nil {
		logger.Errorw("common-utils:Failed to start configuration manager", zap.Error(err))
}
```
While the code is running with a serviceaccount is only bound with a Role:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: pod_name
  namespace: namespacename
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
```
It show that the service account can not list configmaps with cluster scope.
```
E0107 02:18:40.133801       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:namespacename:podname" cannot list resource "configmaps" in API group "" at the cluster scope
```

While after I bind the serviceaccount to a cluster role which has the same rules as the role used above, the error is fixed:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-api-proxy
rules:
- apiGroups:
  - ""
  - extensions
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  - ingresses
  verbs:
  - '*'
```

So my question is that  is a cluster role necessary for running a configmap watcher?
